### ISSUE TITLE
pizza-configuration.js validate bug

### ISSUE THREAD

**Issue by JaimeStill** [backstopmedia/pizza-app#6]
The <code>validate</code> function in <code>src/scripts/models/pizza-configuration.js</code> does not correctly check the size value:

```js
if (!this.size || !this.availableSizes[this.cheese]) {
    errors.size = 'You must select a pizza size';
}
```

Should be:

```js
if (!this.size || !this.availableSizes[this.size]) {
    errors.size = 'You must select a pizza size';
}
```

**Comment by jednano** [comment]
Thanks for pointing this out, @JaimeStill. Do you want to submit a pull request and we'll merge it in?

**Comment by JaimeStill** [comment]
No worries! Done.
